"""initial schema

Revision ID: 5390d0c86915
Revises: 
Create Date: 2026-04-26 12:33:02.241511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5390d0c86915'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kits_name'), ['name'], unique=False)

    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedures_name'), ['name'], unique=True)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_name'), ['name'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=150), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_room_id'), ['room_id'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rfid', sa.String(length=100), nullable=False),
    sa.Column('current_room', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['current_room'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_current_room'), ['current_room'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_rfid'), ['rfid'], unique=True)
        batch_op.create_index(batch_op.f('ix_instruments_status'), ['status'], unique=False)

    op.create_table('procedure_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedure_id', 'step_order')
    )
    with op.batch_alter_table('procedure_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedure_steps_procedure_id'), ['procedure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedure_steps_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedure_steps_step_order'), ['step_order'], unique=False)

    op.create_table('room_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('requirement_value', sa.String(length=255), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_requirements_requirement_type'), ['requirement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_requirements_room_id'), ['room_id'], unique=False)

    op.create_table('instrument_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('from_room_id', sa.Integer(), nullable=True),
    sa.Column('to_room_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['from_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['to_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_history_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_instrument_history_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('kit_instruments',
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('kit_id', 'instrument_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kit_instruments')
    with op.batch_alter_table('instrument_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_history_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_instrument_history_event_type'))

    op.drop_table('instrument_history')
    with op.batch_alter_table('room_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_requirements_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_requirements_requirement_type'))

    op.drop_table('room_requirements')
    with op.batch_alter_table('procedure_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedure_steps_step_order'))
        batch_op.drop_index(batch_op.f('ix_procedure_steps_room_id'))
        batch_op.drop_index(batch_op.f('ix_procedure_steps_procedure_id'))

    op.drop_table('procedure_steps')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_status'))
        batch_op.drop_index(batch_op.f('ix_instruments_rfid'))
        batch_op.drop_index(batch_op.f('ix_instruments_name'))
        batch_op.drop_index(batch_op.f('ix_instruments_current_room'))

    op.drop_table('instruments')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_room_id'))
        batch_op.drop_index(batch_op.f('ix_devices_name'))
        batch_op.drop_index(batch_op.f('ix_devices_mac_address'))

    op.drop_table('devices')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_name'))

    op.drop_table('rooms')
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedures_name'))

    op.drop_table('procedures')
    with op.batch_alter_table('kits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kits_name'))

    op.drop_table('kits')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
