"""initial schema

Revision ID: c9108c28c099
Revises: 
Create Date: 2026-04-24 14:08:17.821976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9108c28c099'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    op.create_table('instrument_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_history_event_type'), 'instrument_history', ['event_type'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rfid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=False)
    op.create_index(op.f('ix_instruments_rfid'), 'instruments', ['rfid'], unique=True)
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kits_name'), 'kits', ['name'], unique=False)
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_name'), 'procedures', ['name'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    op.create_table('kit_instruments',
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('kit_id', 'instrument_id')
    )
    op.create_table('procedure_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_steps_procedure_id'), 'procedure_steps', ['procedure_id'], unique=False)
    op.create_index(op.f('ix_procedure_steps_room_id'), 'procedure_steps', ['room_id'], unique=False)
    op.create_index(op.f('ix_procedure_steps_step_order'), 'procedure_steps', ['step_order'], unique=False)
    op.create_table('room_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('requirement_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_requirements_requirement_type'), 'room_requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('ix_room_requirements_room_id'), 'room_requirements', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_requirements_room_id'), table_name='room_requirements')
    op.drop_index(op.f('ix_room_requirements_requirement_type'), table_name='room_requirements')
    op.drop_table('room_requirements')
    op.drop_index(op.f('ix_procedure_steps_step_order'), table_name='procedure_steps')
    op.drop_index(op.f('ix_procedure_steps_room_id'), table_name='procedure_steps')
    op.drop_index(op.f('ix_procedure_steps_procedure_id'), table_name='procedure_steps')
    op.drop_table('procedure_steps')
    op.drop_table('kit_instruments')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_procedures_name'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_kits_name'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_instruments_rfid'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_instrument_history_event_type'), table_name='instrument_history')
    op.drop_table('instrument_history')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
